# Generated by Django 5.0.5 on 2024-05-07 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trackers_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackersInfoId', models.CharField(blank=True, max_length=1000, null=True)),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('createdAt', models.DateTimeField(default=datetime.datetime.now)),
                ('datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('deliveryProofPhotos', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('dispatcher', models.CharField(blank=True, max_length=1000, null=True)),
                ('driver', models.CharField(blank=True, max_length=1000, null=True)),
                ('driverPhoneNumber', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=1000, null=True)),
                ('equipmentType', models.CharField(blank=True, max_length=1000, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('latestAvailability', models.CharField(blank=True, max_length=1000, null=True)),
                ('loadId', models.CharField(blank=True, max_length=1000, null=True)),
                ('loadStatus', models.CharField(blank=True, max_length=1000, null=True)),
                ('locationLogs', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
